services:

  mysql:
    image: mysql:8.0
    container_name: mysql-enchere2

    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: EnchereAnonyme
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-demo

  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 8085
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-demo
    command:
      - "start-dev"

  angular-app:
    image: angular-enchere1
    container_name: angular
    ports:
      - "4200:80"
    networks:
      - spring-demo

  springboot-app:
    image: enchere-app7
    container_name: spring7
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3307/EnchereAnonyme
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: my-secret-pw
    ports:
      - "8089:8089"
    networks:
      - spring-demo
    depends_on:
      - mysql
      -
networks:
  spring-demo:
    driver: bridge

volumes:
  mysql:
    driver: local